version: "4.0"
services:
  server:
    build: server/
    ports:
      - 8000:8000

  client:
    build: client/
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tonsmall073
      MONGO_INITDB_ROOT_PASSWORD: wisaruth

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8090
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://tonsmall073:wisaruth@mongo:27017/
